### PR TITLE
Use xsd2go to generate all the scap parsers

### PR DESCRIPTION
**Pull request by isimluk**
http://isimluk.com/posts/2020/05/xsd2go-automatically-generate-golang-xml-parsers/

### CODE REVIEW

**Comment by jan-cerny** [comment]
@isimluk Great idea! Can it handle multiple different versions of the schema at the same time? For example multiple versions of OVAL?

**Comment by isimluk** [comment]
Not at this point. See also the first commit message.

**Comment by jan-cerny** [comment]
@isimluk  Aha, sorry, I kind of didn't expect it in a "Revert ..." commit :smile: . Thanks for explanation!

**Comment by isimluk** [comment]
Any update?

**Comment by redhatrises** [comment]
oops... Merging

**Pull request merged**
