### PR TITLE
Create LICENSE

### LINKED ISSUE #6: Missing LICENSE
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

### PR DESCRIPTION
**Pull request by shawndwells**
Resolves https://github.com/ComplianceAsCode/libreSCAP/issues/6

### CODE REVIEW

**Comment by shawndwells** [comment]
Paging @redhatrises and @isimluk

**Comment by TechnologyClassroom** [comment]
I just want to point out that unlicense is a permissive license.  What usually happens with permissive licenses is that companies will use the project in proprietary software and not share their modifications.

I would recommend a copyleft license such as the GPL-3.0-or-later or AGPL-3.0-or-later licenses so that others are encouraged to contribute changes back to your project.

**Comment by shawndwells** [comment]
@TechnologyClassroom yup - completely permissive use is the goal.

**Comment by TechnologyClassroom** [comment]
Why?  Is it intended to be used in proprietary software?

**Comment by isimluk** [comment]
@TechnologyClassroom, I was huge free-software advocate.

But today, I am not convinced that either license makes a huge difference.  The power dynamics of open source world changed significantly about 10 years ago. Software does not need to be distributed/copied to be used anymore. I don't think there is a way to put genie back to the bottle now. Game is over.

**Comment by redhatrises** [comment]
Merging

> Why? Is it intended to be used in proprietary software?

It's intended to have the broadest reach possible including proprietary and non-proprietary functions.

**Pull request merged**
